Option to keep recent events when purging
lingoda/domain-events pull request #10
Opened 2023-02-24 17:51 UTC by TamasSzigeti

Just adding a date arg

2023-02-24 21:02 UTC, balazscsaba2006 requested changes

2023-02-24 21:02 UTC, balazscsaba2006 commented on src/Infra/Doctrine/DoctrineOutboxStore.php
> +        };
These require proper testing of the repository.

2023-06-29 07:26 UTC, kdaniel95 commented
pinging @TamasSzigeti or @balazscsaba2006 in hope this is not a dead PR.

What is the state of this PR? Does it only need repo testing or does anything else need to be added?

2023-06-29 07:31 UTC, balazscsaba2006 commented
> pinging @TamasSzigeti or @balazscsaba2006 in hopes this is not a dead PR.
> 
> What is the state of this PR? Does it only need repo testing or does anything else need to be added?

https://github.com/lingoda/domain-events/pull/10#discussion_r1117643767

2023-06-29 14:56 UTC, kdaniel95 commented
> > pinging @TamasSzigeti or @balazscsaba2006 in hopes this is not a dead PR.
> > What is the state of this PR? Does it only need repo testing or does anything else need to be added?
> 
> [#10 (comment)](https://github.com/lingoda/domain-events/pull/10#discussion_r1117643767)

So functional test on OutboxRecordRepository or on DoctrineOutboxStore? If so, could you provide me with some guidance how it should be done? 
I imagine we create some OutboxRecord, then purge and see if expected records are deleted. I already could achieve creating the schema but cannot really figure out how to populate it (have several problems w/ json_document type for example). 
Thanks for the help!

2023-11-03 14:50 UTC, closed without merging