LW-21356 BE Sync domain-events bundle with main monolith domain-events package changes
lingoda/domain-events pull request #6
Opened 2022-08-23 10:57 UTC by StefanGramadnikov

[Ticket LW-21356](https://lingoda.atlassian.net/browse/LW-21356)

## What have I changed

Sync changes from monolith repo php-package
Added .pre-commit-config.yaml

## Testing instructions
CI Only

## Product changes
N/A

2022-08-23 11:56 UTC, kamilkrajnik submitted a review, later dismissed

2022-08-23 13:51 UTC, kamilkrajnik approved these changes

2022-08-24 09:08 UTC, kamilkrajnik submitted a review, later dismissed

2022-08-24 09:11 UTC, picur requested changes

2022-08-24 09:11 UTC, picur commented on .pre-commit-config.yaml
> +        name: Linguando phpspec
```suggestion
      - id: phpspec
        name: phpspec
```

2022-08-24 09:20 UTC, picur approved these changes

2022-08-24 09:23 UTC, kamilkrajnik approved these changes

2022-08-24 10:58 UTC, kamilkrajnik approved these changes

2022-08-24 11:07 UTC, merged